-- SQL

CREATE TABLE demo1 (A INTEGER NOT NULL PRIMARY KEY, B VARCHAR(100) NOT NULL, C TIMESTAMP NOT NULL);
CREATE TABLE demo2 (A INTEGER NOT NULL PRIMARY KEY, B VARCHAR(100) NOT NULL, C TIMESTAMP NOT NULL);

INSERT INTO demo1(a,b,c)
WITH e1(n) AS
   (SELECT LEVEL l FROM DUAL CONNECT BY LEVEL<11),
e2(n) AS (SELECT 1 FROM e1 CROSS JOIN e1),
e3(n) AS (SELECT 1 FROM e2 CROSS JOIN e2),
e4(n) AS (SELECT 1 FROM e2 CROSS JOIN e3),
xx(n) AS (SELECT ROW_NUMBER() OVER (ORDER BY n) AS x1 FROM e4 ORDER BY n)
SELECT (yy.maxa + xx.n), ('#' || (yy.maxa + xx.n) || ' vals'), SYSTIMESTAMP FROM xx
INNER JOIN (SELECT COALESCE(MAX(a),0) AS maxa FROM demo1) yy ON 1=1;

COMMIT;

INSERT INTO demo2 SELECT * FROM demo1;

COMMIT;

-- End Of File
